import React from 'react';
import { ButtonEmpty } from './ButtonEmpty';

export const ActiveExample: React.FC = () => <ButtonEmpty label="active" />;
export const DisabledExample: React.FC = () => <ButtonEmpty disabled label="disabled" />;
export const PrimaryExample: React.FC = () => <ButtonEmpty color="primary" label="primary" />;
export const SecondaryExample: React.FC = () => <ButtonEmpty color="secondary" label="secondary" />;
export const AccentExample: React.FC = () => <ButtonEmpty color="accent" label="accent" />;
export const SuccessExample: React.FC = () => <ButtonEmpty color="success" label="success" />;
export const WarningExample: React.FC = () => <ButtonEmpty color="warning" label="warning" />;
export const DangerExample: React.FC = () => <ButtonEmpty color="danger" label="danger" />;
export const TextExample: React.FC = () => <ButtonEmpty color="text" label="text" />;
export const GhostExample: React.FC = () => <ButtonEmpty color="ghost" label="ghost" />;
export const BrandGreenExample: React.FC = () => <ButtonEmpty color="brandGreen" label="brandGreen" />;
export const NoFlushExample: React.FC = () => <ButtonEmpty label="no flush" />;
export const FlushLeftExample: React.FC = () => <ButtonEmpty flush="left" label="flush left" />;
export const FlushRightExample: React.FC = () => <ButtonEmpty flush="right" label="flush right" />;
export const FlushBothExample: React.FC = () => <ButtonEmpty flush="both" label="flush both" />;
export const NoHrefExample: React.FC = () => <ButtonEmpty label="no href" />;
export const HrefExample: React.FC = () => <ButtonEmpty href="https://www.google.com" label="has href" />;
export const NoIconExample: React.FC = () => <ButtonEmpty label="no icon" />;
export const IconExample: React.FC = () => <ButtonEmpty iconName="download" label="icon"/>;
export const LeftIconExample: React.FC = () => <ButtonEmpty iconName="download" iconSide="left" label="left" />;
export const RightIconExample: React.FC = () => <ButtonEmpty iconName="download" iconSide="right" label="right" />;
export const NotLoadingExample: React.FC = () => <ButtonEmpty label="not loading" />;
export const LoadingExample: React.FC = () => <ButtonEmpty label="loading" loading />;
export const LargeExample: React.FC = () => <ButtonEmpty label="large" size="l" />;
export const MediumExample: React.FC = () => <ButtonEmpty label="medium" size="m" />;
export const SmallExample: React.FC = () => <ButtonEmpty label="small" size="s" />;
